<?php

function drupalbook_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'book-generate-form') {

    $form['input-name']['#attributes']['placeholder'] = 'API client ID';
 
    $form['#submit'][] = 'drupalbook_settings_submit';
  }
}

function drupalbook_settings_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // drupal_set_message is deprecated
  // drupal_set_message(t('An error occurred and processing did not complete.'));
  \Drupal::messenger()->addStatus('Insert API key in your  tag:  .');
}
